spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:11432/stemp
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 30000

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: prometheus
